# Generated by Django 6.0.3 on 2026-04-22 02:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_fix_album_cover_default_path'),
        ('consumers', '0003_playlist_libraryitem_playlistitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='libraryitem',
            index=models.Index(fields=['-added_at'], name='consumers_l_added_a_51ac34_idx'),
        ),
    ]
