# Generated by Django 6.0.3 on 2026-04-26 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0004_libraryitem_consumers_l_added_a_51ac34_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
