# Generated by Django 6.0.3 on 2026-04-15 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_album_cover_alter_artist_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover',
            field=models.ImageField(default='albums/default.png', upload_to='albums/'),
        ),
    ]
